### ISSUE TITLE
Create a Seed object

### ISSUE THREAD

**Issue by QnJ1c2kNCg** [PortraitOfPine/TheSkyIsTheLimit#3]
* Seeds should _randomly_ spawn near a tree that is adult (need to find that age)
* Seeds stay on the ground and when they hit a certain age (if there is no tree nearby) they transform in to a tree

**Comment by Jerjerzanne** [comment]
- Added two new scripts: Seed and Plant. 
- Tree and Seed both inherit from the Plant class.
- Plant possesses the Grow method that increments the age of both actors. 
I will keep updating the [UML](https://drive.google.com/file/d/1LRX10SpLV_p36rKYwMwmBdz9Kn8pNbVl/view).
